import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import gsap from 'gsap'
import { useEffect } from 'react'

export default function Home() {
  const tl = gsap.timeline({delay: 2.5})

  useEffect (_ => {
    gsap.to('.app-wrapper', {css: {visibility: "visible"}}, 1)
    gsap.to('.head-letter1', {opacity: 1, top: 0, duration: .8}, 1)
    gsap.to('.head-letter2', {opacity: 1, top: 0, duration: .8}, 1.3)
    gsap.to('.head-letter3', {opacity: 1, top: 0, duration: .8}, 1.6)
    gsap.to('.head-letter4', {opacity: 1, top: 0, duration: .8}, 1.9)
    tl.to('.wrapper p', {opacity: 1, duration: .8})
    .to('.main-btn', {opacity: 1, duration: .8}, .7 )
    .to('.video', {opacity: 1, duration: .8}, 1.1 )
    .to('.icon1', {opacity: 1, duration: .8}, 1.3 )
    .to('.icon2', {opacity: 1, duration: .8}, 1.5 )
    .to('.icon3', {opacity: 1, duration: .8}, 2.1 )
    .to('.arrow', {opacity: .6, duration: .8}, 2.1 )
    .to('.arrow.right', {opacity: 1, duration: 2}, 2.1 )
    .to('header', {top: '0', duration: 2}, .6)
  })

  return (
    <div className='app-wrapper'>
      <Head>
        <title>Grow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;900&display=swap" rel="stylesheet" />
      </Head>

      <header>
        <div className="container">
          
          <Link href='/'><a>
            <div className='logo'>
              <Image src='/images/logo.svg' width={652.05} height={74.35} />
            </div>
          </a></Link>

          <div className='menu-icon'>
            <Image src='/images/menu.svg' width={90} height={36} />
          </div>

          <ul className='nav-items'>
            <li className='nav-item'>Main</li>
            <li className='nav-item active'>Info</li>
            <li className='nav-item'>Contact</li>
            <li className='nav-item cta-btn'>Plant Now</li>
          </ul>

        </div>
      </header>

      <main>
        <div className="container">

          <div className='arrow'>
            <div className='arrow-image'>
              <Image src='/images/arrow.svg' width={42} height={42.02} />
            </div>
          </div>
          <div className='arrow right'>
            <div className='arrow-round'></div>
            <div className='arrow-image'>
              <Image src='/images/arrow.svg' width={42} height={42.02} />
            </div>
          </div>

          <div className='branch'></div>

          <div className="wrapper">
            <h1>
              <span className='head-group'>
                <span className='head-letter head-letter1'>G</span>
                <span className='head-letter head-letter2'>R</span>
              </span>
              <span className='head-group'>
                <span className='head-letter head-letter3'>O</span>
                <span className='head-letter head-letter4'>W</span>
              </span>
            </h1>

            <p>As an environmental charity, we’re on a mission to make it simple for everyone to help the environment by planting each one tree!</p>

            <button className='main-btn'>PLANT A TREE NOW</button>
          </div>

          <div className='video'>
            <div></div>
            <div></div>
            <div>
              <div>
                <Image src='/images/play.png' width={30} height={40} />
              </div>
            </div>
          </div>

          <div className='social-icons'>
            <div className='icon1'>
              <Image src='/images/facebook.png' width={63.94} height={63.94} />
            </div>
            <div className='icon2'>
              <Image src='/images/instagram.png' width={63.94} height={63.94} />
            </div>
            <div className='icon3'>
              <Image src='/images/youtube.png' width={63.95} height={63.95} />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
