import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;900&display=swap" rel="stylesheet" />
      </Head>

      <header>
        <div className="container">
          
          <Link href='/'><a>
            <div className='logo'>
              <Image src='/images/logo.svg' width={652.05} height={74.35} />
            </div>
          </a></Link>

          <div className='menu-icon'>
            <Image src='/images/menu.svg' width={90} height={36} />
          </div>

          <ul className='nav-items'>
            <li className='nav-item'>Main</li>
            <li className='nav-item active'>Info</li>
            <li className='nav-item'>Contact</li>
            <li className='nav-item cta-btn'>Plant Now</li>
          </ul>

        </div>
      </header>

      <main>
        <div className="container">

          <div className='arrow'>
            <div className='arrow-image'>
              <Image src='/images/arrow.svg' width={42} height={42.02} />
            </div>
          </div>
          <div className='arrow right'>
            <div className='arrow-round'></div>
            <div className='arrow-image'>
              <Image src='/images/arrow.svg' width={42} height={42.02} />
            </div>
          </div>

          <div className='branch'></div>

          <div className="wrapper">
            <h1>
              <span className='head-group'>
                <span className='head-letter'>G</span>
                <span className='head-letter'>R</span>
              </span>
              <span className='head-group'>
                <span className='head-letter'>O</span>
                <span className='head-letter'>W</span>
              </span>
            </h1>

            <p>As an environmental charity, we’re on a mission to make it simple for everyone to help the environment by planting each one tree!</p>

            <button className='main-btn'>PLANT A TREE NOW</button>
          </div>

          <div className='video'>
            <div></div>
            <div></div>
            <div>
              <div>
                <Image src='/images/play.png' width={30} height={40} />
              </div>
            </div>
          </div>

          <div className='social-icons'>
            <div>
              <Image src='/images/facebook.png' width={63.94} height={63.94} />
            </div>
            <div>
              <Image src='/images/instagram.png' width={63.94} height={63.94} />
            </div>
            <div>
              <Image src='/images/youtube.png' width={63.95} height={63.95} />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
